spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  application:
    name: dofarming


jwt:
  issuer: dofarming@dofarming.com
  secret_key: ${JWT_SECRET_KEY}
  expiration: ${ACCESS_TOKEN_EXPIRATION} #86400000
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION} #604800000


# s3
cloud:
  aws:
    s3:
      bucket: campus-note-storage
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}